[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "chatbot"
version = "0.1.3"
description = "A chat bot that helps you manage your contacts, notes and sort files in folders."
dependencies = ["prompt-toolkit>=3.0.41", "wcwidth>=0.2.10"]
